var databaza =
  'SET NAMES utf8; '
  + ' SET time_zone = \'+00:00\'; '
  + ' SET foreign_key_checks = 0; '
  + ' SET sql_mode = \'NO_AUTO_VALUE_ON_ZERO\'; '

  + ' DROP TABLE IF EXISTS `kosik`;'
  + ' CREATE TABLE `kosik` ('
  + '   `id` int unsigned NOT NULL AUTO_INCREMENT,'
  + '   `pocet_produktov` int unsigned NOT NULL,'
  + '   `produkt_id` int unsigned NOT NULL,'
  + '   `objednavka_id` int unsigned NOT NULL,'
  + '   PRIMARY KEY (`id`),'
  + '   KEY `produkt_id` (`produkt_id`),'
  + '   KEY `objednavka_id` (`objednavka_id`),'
  + '   CONSTRAINT `kosik_ibfk_1` FOREIGN KEY (`produkt_id`) REFERENCES `produkt` (`id`),'
  + '   CONSTRAINT `kosik_ibfk_2` FOREIGN KEY (`objednavka_id`) REFERENCES `objednavka` (`id`)'
  + ' ) ENGINE=InnoDB DEFAULT CHARSET=utf8;'


  + ' DROP TABLE IF EXISTS `objednavka`;'
  + ' CREATE TABLE `objednavka` ('
  + '   `id` int unsigned NOT NULL AUTO_INCREMENT,'
  + '   `zakaznik_id` int unsigned NOT NULL,'
  + '   PRIMARY KEY (`id`),'
  + '   KEY `zakaznik_id` (`zakaznik_id`),'
  + '   CONSTRAINT `objednavka_ibfk_1` FOREIGN KEY (`zakaznik_id`) REFERENCES `zakaznik` (`id`)'
  + ' ) ENGINE=InnoDB DEFAULT CHARSET=utf8;'


  + ' DROP TABLE IF EXISTS `produkt`;'
  + ' CREATE TABLE `produkt` ('
  + '   `id` int unsigned NOT NULL AUTO_INCREMENT,'
  + '   `nazov` varchar(30) NOT NULL,'
  + '   `obrazok` tinytext NOT NULL,'
  + '   `cena` double NOT NULL,'
  + '   PRIMARY KEY (`id`)'
  + ' ) ENGINE=InnoDB DEFAULT CHARSET=utf8;'

  + ' DROP TABLE IF EXISTS `zakaznik`;'
  + ' CREATE TABLE `zakaznik` ('
  + '   `id` int unsigned NOT NULL AUTO_INCREMENT,'
  + '   `meno` varchar(50) NOT NULL,'
  + '   `ulica` varchar(40) NOT NULL,'
  + '   `cislo` int NOT NULL,'
  + '   `mesto` varchar(30) NOT NULL,'
  + '   `psc` int NOT NULL,'
  + '   PRIMARY KEY (`id`)'
  + ' ) ENGINE=InnoDB DEFAULT CHARSET=utf8;'

  + ' INSERT INTO `zakaznik` (`id`, `meno`, `ulica`, `cislo`, `mesto`, `psc`) VALUES'
  + ' (1,	\'admin\',	\'Iklovicova\',	2,	\'BA\',	12345);'